repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
    - id: isort
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      additional_dependencies: [pydantic]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
    - id: markdown-toc
      files: ^README.md$
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    - id: blacken-docs
      additional_dependencies: [black==21.7b0]
