name: release

on:
  push:
    tags:
      - "*"

env:
  POETRY_VERSION: "1.7.1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Release package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
